inherit_from:
  - .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数の上限を８０文字から変更
LineLength:
  Max: 130

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 6.1.4
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'